version: '3'

services:
  node:
    build: .
    environment:
      - ETH_NETWORK=polygon
      - INFURA_API_KEY=<Your Infura API Key>
      - PRIVATE_KEY=<Your Private Key>
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start

  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
    command: ["--routing=dhtclient", "--enable-namesys-pubsub", "--enable-gc", "--migrate"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

